{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.3.3"
    }
  },
  "component" : {
    "group" : "com.github.jeziellago",
    "module" : "Markwon",
    "version" : "58aa5aba6a",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "io.coil-kt",
      "module" : "coil-base",
      "version" : {
        "requires" : "2.2.2"
      }
    } ],
    "files" : [ {
      "name" : "Markwon-58aa5aba6a.aar",
      "url" : "Markwon-58aa5aba6a.aar",
      "size" : 18159,
      "sha512" : "d0ba577ca84b9647b467a164ecfeff36b34caf340536ad0b7362caf7d4dcc7eb43bf2f1c26b32b23c2114e8db6337af664c63eb48bd36689fba78f6f0b279d32",
      "sha256" : "765985e2e159bcf9676c98b4d442924f6a94f3e333090f1e2d616aaff5e62072",
      "sha1" : "4bc48a52bed576e43774a3b5f95d69d03cf7a36d",
      "md5" : "fbb2b97499451c5de74e3142e3445b37"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "io.noties.markwon",
      "module" : "core",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.coil-kt",
      "module" : "coil-base",
      "version" : {
        "requires" : "2.2.2"
      }
    } ],
    "files" : [ {
      "name" : "Markwon-58aa5aba6a.aar",
      "url" : "Markwon-58aa5aba6a.aar",
      "size" : 18159,
      "sha512" : "d0ba577ca84b9647b467a164ecfeff36b34caf340536ad0b7362caf7d4dcc7eb43bf2f1c26b32b23c2114e8db6337af664c63eb48bd36689fba78f6f0b279d32",
      "sha256" : "765985e2e159bcf9676c98b4d442924f6a94f3e333090f1e2d616aaff5e62072",
      "sha1" : "4bc48a52bed576e43774a3b5f95d69d03cf7a36d",
      "md5" : "fbb2b97499451c5de74e3142e3445b37"
    } ]
  } ]
}