{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.7"
    }
  },
  "component" : {
    "group" : "com.github.jeziellago",
    "module" : "compose-markdown",
    "version" : "0.5.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiElements-published",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "dependencies" : [ {
      "group" : "io.coil-kt",
      "module" : "coil",
      "version" : {
        "requires" : "2.6.0"
      }
    }, {
      "group" : "io.coil-kt",
      "module" : "coil-gif",
      "version" : {
        "requires" : "2.6.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "1.9.23"
      }
    } ],
    "files" : [ {
      "name" : "compose-markdown-0.5.6.aar",
      "url" : "compose-markdown-0.5.6.aar",
      "size" : 70656,
      "sha512" : "92d12008fe559984080b4ccbb14299d2bfc9ca58bed2947a61a23b843d4a4d1a9b1b574ea608c7ab284cafb5d5917ecfa8c19cd74c40c69a7299201a945f2494",
      "sha256" : "d7054c3c08a28855fbeeaf0ae36216ca17d54630ff75354bbd357337a067857c",
      "sha1" : "cc159569058dbe33274de92a4c84d1f42e6d6cd8",
      "md5" : "9166142f46051a2f50edc656130a81f6"
    } ]
  }, {
    "name" : "releaseRuntimeElements-published",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "dependencies" : [ {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.13.1"
      }
    }, {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.7.0"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "core",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "ext-strikethrough",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "ext-tables",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "html",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "linkify",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "io.noties.markwon",
      "module" : "ext-tasklist",
      "version" : {
        "requires" : "4.6.2"
      }
    }, {
      "group" : "com.github.jeziellago",
      "module" : "Markwon",
      "version" : {
        "requires" : "58aa5aba6a"
      }
    }, {
      "group" : "androidx.compose.ui",
      "module" : "ui",
      "version" : {
        "requires" : "1.6.6"
      }
    }, {
      "group" : "androidx.compose.material3",
      "module" : "material3",
      "version" : {
        "requires" : "1.2.1"
      }
    }, {
      "group" : "io.coil-kt",
      "module" : "coil",
      "version" : {
        "requires" : "2.6.0"
      }
    }, {
      "group" : "io.coil-kt",
      "module" : "coil-gif",
      "version" : {
        "requires" : "2.6.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "1.9.23"
      }
    } ],
    "files" : [ {
      "name" : "compose-markdown-0.5.6.aar",
      "url" : "compose-markdown-0.5.6.aar",
      "size" : 70656,
      "sha512" : "92d12008fe559984080b4ccbb14299d2bfc9ca58bed2947a61a23b843d4a4d1a9b1b574ea608c7ab284cafb5d5917ecfa8c19cd74c40c69a7299201a945f2494",
      "sha256" : "d7054c3c08a28855fbeeaf0ae36216ca17d54630ff75354bbd357337a067857c",
      "sha1" : "cc159569058dbe33274de92a4c84d1f42e6d6cd8",
      "md5" : "9166142f46051a2f50edc656130a81f6"
    } ]
  }, {
    "name" : "releaseSourcesElements-published",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "files" : [ {
      "name" : "compose-markdown-0.5.6.jar",
      "url" : "compose-markdown-0.5.6.jar",
      "size" : 27593,
      "sha512" : "fc9740b3b25bff5d7e34c5d293278c19998be99a4aa3d111a9f561d118abfaacfb78b792e09571625dd25f47de8534150f17a8d59bfd28c23f610a68c19ca76e",
      "sha256" : "d4fc1a82f2127d6a1cf11db8e7b4200d9434163179b6b2cc5f327068f4fe476c",
      "sha1" : "69dd23cc321c3511dbe967054689a688eea6c03f",
      "md5" : "becad6ce3e28c2a1d129c785ad333b79"
    } ]
  } ]
}